name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    description: 'S3 Bucket name'
    required: false
    default: 'TEST_BUCKET'
  bucket-region:
    description: 'The buckets region'
    requirde: false
    default: 'TEST_REGION'
  dis-folder:
    description: 'Path to the folder containing the deployable files'
    required: true
outputs:
  url:
    description: 'An URL'
runs:
  using: 'node16'
  main: 'main.js'
